# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
# musicbrainz_20092010
postgres_development:
  adapter: postgresql
  database: wex
  host: 127.0.0.1
  username: postgres
  password: wa3Ub8ji
  pool: 5
  timeout: 5000
  reconnect: true


development:  
  adapter: mysql
  database: kazaa_similar_artists
#  host: 216.240.131.186
  host: 127.0.0.1
#  host: 192.168.26.79
  username: root
  password: 'Mon Aug 10 23:19:09 CDT 2009'
#  password: bah5ieMoTahphau8vaa5Caep  
  pool: 5
  timeout: 5000
  reconnect: true

  # adapter: mysql
  # database: kazaa_similar_artists
  # host: 216.240.131.186
  # username: root
  # password: 'Mon Aug 10 23:19:09 CDT 2009'  
  # pool: 5
  # timeout: 5000
  # reconnect: true

        
  # adapter: mysql
  # database: music_social_production
  # host: 192.168.26.79
  # password: bah5ieMoTahphau8vaa5Caep
  # username: root
  # pool: 5
  # timeout: 5000
  # reconnect: true

